config/routes.rb
Rails.application.routes.draw do
  root 'principal#index'

  get 'principal/services'
  get 'principal/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  end

  def services
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TV SATURNO - TIJUANA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">TV-Saturno</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: 'nav-link' %>
        </li>
<!--        <li class="nav-item">-->
          <%#= link_to "Servicios",  principal_services_path, class: 'nav-link' %>
<!--        </li>-->
        <li class="nav-item">
          <%= link_to "Contacto",  principal_contact_path, class: 'nav-link' %>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
    <div class="container" id="container">
      <%= yield %>
    </div>

  <footer id="myFooter">
    <div class="container">
<!--      <div class="row">-->
<!--        <div class="col-sm-3">-->
<!--          <h2 class="logo"><a href="#"> LOGO </a></h2>-->
<!--        </div>-->
<!--        <div class="col-sm-2">-->
<!--          <h5>Get started</h5>-->
<!--          <ul>-->
<!--            <li><a href="#">Home</a></li>-->
<!--            <li><a href="#">Sign up</a></li>-->
<!--            <li><a href="#">Downloads</a></li>-->
<!--          </ul>-->
<!--        </div>-->
<!--        <div class="col-sm-2">-->
<!--          <h5>About us</h5>-->
<!--          <ul>-->
<!--            <li><a href="#">Company Information</a></li>-->
<!--            <li><a href="#">Contact us</a></li>-->
<!--            <li><a href="#">Reviews</a></li>-->
<!--          </ul>-->
<!--        </div>-->
<!--        <div class="col-sm-2">-->
<!--          <h5>Support</h5>-->
<!--          <ul>-->
<!--            <li><a href="#">FAQ</a></li>-->
<!--            <li><a href="#">Help desk</a></li>-->
<!--            <li><a href="#">Forums</a></li>-->
<!--          </ul>-->
<!--        </div>-->
<!--        <div class="col-sm-3">-->
<!--          <div class="social-networks">-->
<!--            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>-->
<!--            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>-->
<!--            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>-->
<!--          </div>-->
<!--          <button type="button" class="btn btn-default">Contact us</button>-->
<!--        </div>-->
<!--      </div>-->
    </div>
    <div class="footer-copyright">
      <p>© 2018 Copyright Tv-Saturno </p>
    </div>
  </footer>


  </body>
</html>

app/views/principal/contact.html.erb
<h1>Principal#contact</h1>
<p>Find me in app/views/principal/contact.html.erb</p>

app/views/principal/index.html.erb
<h1>Bienvenidos a TV-SATURNO</h1>
<div class="row">
  <div class="col-md-4">
    <figure class="figure ">
      <img src="https://via.placeholder.com/400x300?text=TV-Saturn" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure.">
      <figcaption class="figure-caption">Imagen de la empresa.</figcaption>
    </figure>
  </div>


  <div class="col-md-8 lead">
    En TV-Saturno contamos con xx años de experiencia en el reparación de aparatos eléctronicos

    <p>
      <ul>
        <li>Televiciones CRT</li>
        <li>Televiciones LED</li>
        <li>Televiciones Plasma</li>
        <li>Estereos</li>
        <li>Bocinas</li>

      </ul>
    </p>
    <p>

    </p>


  </div>

</div>

app/views/principal/services.html.erb
<h1>Principal#services</h1>
<p>Find me in app/views/principal/services.html.erb</p>